---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/signup":
    post:
      summary: Create a user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: Signed up sucessfully.
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: email
                password:
                  type: string
              required:
              - id
              - name
              - email
              - password
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3001
